# Generated by Django 5.0.6 on 2024-06-19 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orienteering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racerunner',
            name='total_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
